{
  config,
  flake-parts-lib,
  lib,
  inputs,
  ...
}:
let
  inherit (builtins)
    toString
    ;

  infix-lib = import ../lib {
    inherit
      lib
      ;
  };

  inherit (infix-lib)
    dirToAttrs
    mapAttrsRecursive'
    mapAttrsRecursiveCond'
    stemOf
    ;

  inherit (lib)
    filterAttrsRecursive
    hasAttr
    hasSuffix
    isAttrs
    last
    mapAttrs
    mapAttrsToList
    mapAttrsToListRecursive
    mkDefault
    mkOption
    nameValuePair
    pathExists
    pipe
    types
    ;

  hasInput =
    input:
    if hasAttr input inputs then
      inputs.${input}
    else
      throw ''
        ${input} input not found, please add a ${input} input to your flake.
      '';

  disko = hasInput "disko";

  facter = hasInput "facter";

  home-manager = hasInput "home-manager";

  nixpkgs = hasInput "nixpkgs";

  nixosConfigurationModule =
    {
      config,
      ...
    }:
    let
      userModule =
        {
          config,
          ...
        }:
        {
          options = {
            directory = mkOption {
              description = ''
                The Home Configuration directory.
              '';

              type = types.path;
            };

            etcDirectory = mkOption {
              defaultText = "${config.directory}/etc";

              description = ''
                The directory beneath which user-wide configuration files.
              '';

              type = types.path;
            };

            homeFile = mkOption {
              defaultText = "${config.directory}/home.nix";

              description = ''
                The top-level Home Configuration File.
              '';

              type = types.path;
            };

            modules = mkOption {
              default = [ ];

              description = ''
                Extra Home modules applied to the Home Configuration.

                Accepts module paths,  or inline module functions.
              '';

              type = with types; listOf deferredModule;
            };

            modulesDirectory = mkOption {
              defaultText = "${config.directory}/modules";

              description = ''
                The directory beneath which user-wide Home modules.
              '';

              type = types.path;
            };

            profiles = mkOption {
              default = [ ];

              description = ''
                Extra Home profiles applied to the Home Configuration.

                Inhere profiles are config-only module, accepts module paths, or
                inline module functions.
              '';

              type = with types; listOf deferredModule;
            };

            profilesDirectory = mkOption {
              defaultText = "${config.directory}/profiles";

              description = ''
                The directory beneath which user-wide Home profiles.
              '';

              type = types.path;
            };

            userFile = mkOption {
              defaultText = "${config.directory}/user.nix";

              description = ''
                The user declaration file for NixOS Configuration.
              '';

              type = types.path;
            };
          };

          config = {
            etcDirectory = mkDefault (
              config.directory + /etc
            );

            homeFile = mkDefault (
              config.directory + /home.nix
            );

            modulesDirectory = mkDefault (
              config.directory + /modules
            );

            profilesDirectory = mkDefault (
              config.directory + /profiles
            );

            userFile = mkDefault (
              config.directory + /user.nix
            );
          };
        };
    in
    {
      options = {
        directory = mkOption {
          description = ''
            The NixOS Configuration directory.
          '';

          type = types.path;
        };

        diskoFile = mkOption {
          defaultText = "${config.directory}/disko.nix";

          description = ''
            The filesystems declaration file (by Disko).
          '';

          type = types.path;
        };

        etcDirectory = mkOption {
          defaultText = "${config.directory}/etc";

          description = ''
            The directory beneath which system-wide configuraiton files.
          '';

          type = types.path;
        };

        facterReportFile = mkOption {
          defaultText = "${config.directory}/etc/facter.json";

          description = ''
            Path to a report generated by nixos-facter.
          '';

          type = types.path;
        };

        modules = mkOption {
          default = [ ];

          description = ''
            Extra NixOS modules applied to the NixOS Configuration.

            Accepts module paths,  or inline module functions.
          '';

          type = with types; listOf deferredModule;
        };

        modulesDirectory = mkOption {
          defaultText = "${config.directory}/modules";

          description = ''
            The directory beneath which system-wide NixOS modules.
          '';

          type = types.path;
        };

        profiles = mkOption {
          default = [ ];

          description = ''
            Extra NixOS profiles applied to the NixOS Configuration.

            Inhere profiles are config-only module, accepts module paths, or
            inline module functions.
          '';

          type = with types; listOf deferredModule;
        };

        profilesDirectory = mkOption {
          defaultText = "${config.directory}/profiles";

          description = ''
            The directory beneath which system-wide NixOS profiles.
          '';

          type = types.path;
        };

        specialArgs = mkOption {
          default = { };

          description = ''
            Special arguments to pass to NixOS Configuration.
          '';

          type = types.attrsOf types.anything;
        };

        systemFile = mkOption {
          defaultText = "${config.directory}/system.nix";

          description = ''
            The top-level NixOS Configuration File.
          '';

          type = types.path;
        };

        users = mkOption {
          default = { };

          description = ''
            The User Configurations.
          '';

          type =
            with types;
            lazyAttrsOf (submoduleWith {
              modules = [
                userModule
              ];
            });
        };
      };

      config = {
        diskoFile = mkDefault (
          config.directory + /disko.nix
        );

        etcDirectory = mkDefault (
          config.directory + /etc
        );

        facterReportFile = mkDefault (
          config.directory + /etc/facter.json
        );

        modulesDirectory = mkDefault (
          config.directory + /modules
        );

        profilesDirectory = mkDefault (
          config.directory + /profiles
        );

        systemFile = mkDefault (
          config.directory + /system.nix
        );
      };
    };

  mkNixOSConfiguration =
    name:
    value@{
      directory,
      diskoFile,
      etcDirectory,
      facterReportFile,
      modules,
      modulesDirectory,
      profiles,
      profilesDirectory,
      specialArgs,
      systemFile,
      users,
      ...
    }:
    let
      dirToAttrs' =
        dir:
        if pathExists dir then
          pipe (dirToAttrs dir) [
            (filterAttrsRecursive (
              _: v:
              if isAttrs v then
                true
              else
                hasSuffix ".nix" (toString v)
            ))
            (mapAttrsRecursiveCond'
              (v: !(isAttrs v && v ? default))
              (
                path: v:
                nameValuePair (stemOf (last path)) (
                  if isAttrs v && v ? default then v.default else v
                )
              )
            )
          ]
        else
          { };

      etcDirToAttrs =
        dir:
        if pathExists dir then
          pipe (dirToAttrs dir) [
            (mapAttrsRecursive' (
              path: value:
              if (last path) == "__path" then
                nameValuePair "__path" value
              else
                nameValuePair (stemOf (last path)) value
            ))
          ]
        else
          { };

      dirToList =
        dir:
        mapAttrsToListRecursive (_: v: v) (
          dirToAttrs' dir
        );

      userModuleList =
        (mapAttrsToList (_: v: v.userFile) users)
        ++ (mapAttrsToList (n: v: {
          home-manager = {
            users = {
              ${n} =
                { ... }:
                {
                  imports =
                    v.modules
                    ++ (dirToList v.modulesDirectory)
                    ++ [ v.homeFile ]
                    ++ v.profiles
                    ++ (dirToList v.profilesDirectory);
                };
            };
          };
        }) users);

      usersSpecialArgs = mapAttrs (_: v: {
        etc = etcDirToAttrs v.etcDirectory;
        modules = dirToAttrs' v.modulesDirectory;
        profiles = dirToAttrs' v.profilesDirectory;
      }) users;

      finalSpecialArgs = {
        inherit
          inputs
          ;
      }
      // specialArgs
      // {
        ${name} = {
          etc = etcDirToAttrs etcDirectory;
          modules = dirToAttrs' modulesDirectory;
          profiles = dirToAttrs' profilesDirectory;
        };
      }
      // usersSpecialArgs;

      finalModules = [
        {
          networking = {
            hostName = mkDefault "${name}";
          };
        }
        disko.nixosModules.disko
        diskoFile
        facter.nixosModules.facter
        {
          facter = {
            reportPath = facterReportFile;
          };
        }
      ]
      ++ modules
      ++ (dirToList modulesDirectory)
      ++ [
        systemFile
      ]
      ++ profiles
      ++ (dirToList profilesDirectory)
      ++ [
        home-manager.nixosModules.home-manager
        {
          home-manager = {
            extraSpecialArgs = finalSpecialArgs;
          };
        }
      ]
      ++ userModuleList;
    in
    nixpkgs.lib.nixosSystem {
      modules = finalModules;
      specialArgs = finalSpecialArgs;
    };
in
{
  options = {
    nixosConfigurations = mkOption {
      default = { };

      description = ''
        The NixOS Configurations.
      '';

      type =
        with types;
        lazyAttrsOf (submoduleWith {
          modules = [
            nixosConfigurationModule
          ];
        });
    };
  };

  config = {
    flake = {
      nixosConfigurations = mapAttrs mkNixOSConfiguration config.nixosConfigurations;
    };
  };
}
